### ISSUE TITLE
spurious % on %name string

### ISSUE THREAD

**Issue by max-privato** [modelica-3rdparty/PowerSystems#46]
In several models (e.g. Examples.PowerWorld.Components.HydroPlant) the name I read for the model name textString="%name%", while it should be textString="%name", instead (see. Modelica spec 3.4 sect. 18.6.5.5).
Note that this mistake does not cause visualization errors in Dymola, while causes an erroneous "% to be shown in OpenModelica.

**Comment by rfranke** [comment]
Thank you for the hint!
